// <auto-generated />
using System;
using Cantor.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Cantor.Infrastructure.Migrations
{
    [DbContext(typeof(CantorContext))]
    [Migration("20210927132005_UserIdAdded")]
    partial class UserIdAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Cantor.Application.Entities.InvestmentPortfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CzkAmount")
                        .HasColumnType("integer");

                    b.Property<int>("EurAmount")
                        .HasColumnType("integer");

                    b.Property<int>("GbpAmount")
                        .HasColumnType("integer");

                    b.Property<int>("PlnAmount")
                        .HasColumnType("integer");

                    b.Property<int>("UsdAmount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
